Env: "local"

DatabaseSettings:
  DatabaseURI: "root:root@tcp(127.0.0.1:3306)/picus_shop"
  DatabaseName: "LOCALpicus_shop"
  Username: "LOCALroot"
  Password: "LOCALroot"

JwtSettings:
  SecretKey: ""

RedisSettings:
  AddrURI: "127.0.0.1:6379"


#Env: "prod"

  #NewRelicSettings:
  #LicenseKey: "YOUR_LICENSE_KEY"
  #AppName: "YOUR_PROD_APP_NAME"
